version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    restart: unless-stopped
    labels:
      caddy.email: ${CADDY_EMAIL}

networks:
  caddy:
    external: true

volumes:
  data:
    driver_opts:
      type: none
      device: ${PROJECT_PATH}/data/caddy
      o: bind
